# Generated by Django 6.0.7 on 2026-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biomaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('applications', models.TextField()),
            ],
        ),
    ]
