# Generated by Django 6.0.7 on 2026-07-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomaterials', '0002_biomaterial_created_at_biomaterial_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomaterial',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
