# Generated by Django 6.0.7 on 2026-07-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomaterials', '0003_biomaterial_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomaterial',
            name='chebi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='molecular_formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='molecular_weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='pubchem_cid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='structure_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='applications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
