# Generated by Django 6.0.7 on 2026-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomaterials', '0004_biomaterial_chebi_id_biomaterial_molecular_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomaterial',
            name='biocompatibility',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='biodegradability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='chemical_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='doi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='mechanical_strength',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='pubmed_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='sem_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='thermal_stability',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
