# Generated by Django 6.0.7 on 2026-07-13 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0002_alter_protein_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
