# Generated by Django 6.0.7 on 2026-07-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=200)),
                ('uniprot_id', models.CharField(max_length=20, unique=True)),
                ('pdb_id', models.CharField(blank=True, max_length=10)),
                ('organism', models.CharField(max_length=200)),
                ('sequence', models.TextField()),
                ('molecular_weight', models.FloatField()),
                ('function', models.TextField()),
            ],
        ),
    ]
