# Generated by Django 6.0.7 on 2026-07-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='function',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='molecular_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
