# Generated by Django 6.0.7 on 2026-07-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biomaterials', '0001_initial'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_energy', models.FloatField()),
                ('interaction_type', models.CharField(max_length=100)),
                ('reference', models.TextField()),
                ('biomaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomaterials.biomaterial')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.protein')),
            ],
        ),
    ]
