# Generated by Django 6.0.7 on 2026-07-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='docking_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
